-- Création des utilisateurs dans le conteneur actuel (PDB)
CREATE USER ADMIN_USER IDENTIFIED BY admin_password CONTAINER=CURRENT;
CREATE USER MANAGER_USER IDENTIFIED BY manager_password CONTAINER=CURRENT;
CREATE USER REGULAR_USER IDENTIFIED BY regular_password CONTAINER=CURRENT;


GRANT CONNECT, RESOURCE TO ADMIN_USER CONTAINER=CURRENT;
GRANT CONNECT, RESOURCE TO MANAGER_USER CONTAINER=CURRENT;
GRANT CONNECT TO REGULAR_USER CONTAINER=CURRENT;

-- Vérification
SELECT USERNAME FROM DBA_USERS WHERE USERNAME IN ('ADMIN_USER', 'MANAGER_USER', 'REGULAR_USER');